Feat/SP-931 Add CycloneDX export
scanoss/sbom-workbench pull request #759
Opened 2024-06-27 13:55 UTC by isasmendiagus

* Adds the option to export a CycloneDX SBOM

2024-06-28 12:28 UTC, agustingroh commented on src/main/task/export/Export.ts
> +import { workspace } from '../../workspace/Workspace';
Should we add the ExportModel and project in all the formats in the future?

2024-06-28 12:38 UTC, agustingroh requested changes
I tried to export the CycloneDX from the detected and identified section but the UI is throwing the following error.
I made the following steps before test the branch:
- npm  install --legacy-peer-deps
- npm run




![image](https://github.com/scanoss/sbom-workbench/assets/77737320/82af3d76-f911-47cf-b532-b789ef1d870d)

![image](https://github.com/scanoss/sbom-workbench/assets/77737320/978e589e-36c9-4f1f-aecf-a46691275468)

2024-07-01 07:40 UTC, isasmendiagus commented
> I tried to export the CycloneDX from the detected and identified section but the UI is throwing the following error. I made the following steps before test the branch:
> 
>     * npm  install --legacy-peer-deps
> 
>     * npm run
> 
> 
> ![image](https://private-user-images.githubusercontent.com/77737320/344163476-82af3d76-f911-47cf-b532-b789ef1d870d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTk0NDYsIm5iZiI6MTcxOTgxOTE0NiwicGF0aCI6Ii83NzczNzMyMC8zNDQxNjM0NzYtODJhZjNkNzYtZjkxMS00N2NmLWI1MzItYjc4OWVmMWQ4NzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA3MzIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MjkyYzdiNjUxMmNhNmM4YzA5ZTMxM2Y2YmE5ZWI2ZTAzMzgwMmFkZWRmYThkOWU2N2QzMzBmYTE4ZWEwZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IPU68hvXLB-L7A9QQajz00wI3pPiodHVjTc8bavzZFI)
> 
> ![image](https://private-user-images.githubusercontent.com/77737320/344163565-978e589e-36c9-4f1f-aecf-a46691275468.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTk0NDYsIm5iZiI6MTcxOTgxOTE0NiwicGF0aCI6Ii83NzczNzMyMC8zNDQxNjM1NjUtOTc4ZTU4OWUtMzZjOS00ZjFmLWFlY2YtYTQ2NjkxMjc1NDY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA3MzIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMjI1OTMyMjRlMmYxZTgxMTEwNzZkZjUxZWQyYWIzOGM5NmVlN2IwOWZkYWU0MTEwNGQ3YzM0OTdlMjU5YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iYjFRMzqn6K-V3vFrKHKc1uJecGxDxHN1omcZBQmgoM)

There was a silly bug. The license declared when you start a new project it's optional, that caused the crash

2024-07-01 16:28 UTC, isasmendiagus commented on src/main/task/export/Export.ts
> +import { workspace } from '../../workspace/Workspace';
Yes, this will allow us to test individually each Export class

2024-07-01 16:28 UTC, isasmendiagus commented
> I tried to export the CycloneDX from the detected and identified section but the UI is throwing the following error. I made the following steps before test the branch:
> 
>     * npm  install --legacy-peer-deps
> 
>     * npm run
> 
> 
> ![image](https://private-user-images.githubusercontent.com/77737320/344163476-82af3d76-f911-47cf-b532-b789ef1d870d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NTE1MjYsIm5iZiI6MTcxOTg1MTIyNiwicGF0aCI6Ii83NzczNzMyMC8zNDQxNjM0NzYtODJhZjNkNzYtZjkxMS00N2NmLWI1MzItYjc4OWVmMWQ4NzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDE2MjcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMjIzOTk4NDFlZWViMzViMTdjZDVjNjgxOGRhMWE3NWU3NDJkNTMzZTFiNGRmOTY0M2ZmMmQxYjM4ZTQ3OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YWqEs8pFQOn_Rax7Gqla_YXbfY3QRLQcICpqDOHJO-w)
> 
> ![image](https://private-user-images.githubusercontent.com/77737320/344163565-978e589e-36c9-4f1f-aecf-a46691275468.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NTE1MjYsIm5iZiI6MTcxOTg1MTIyNiwicGF0aCI6Ii83NzczNzMyMC8zNDQxNjM1NjUtOTc4ZTU4OWUtMzZjOS00ZjFmLWFlY2YtYTQ2NjkxMjc1NDY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDE2MjcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkN2E3YWUwN2Y4NjJiMjJmZTgyNTZlZTQ0NjNjZTgzNTNiZDU0MWRiMjI0MGVkZjM5OGIxNDJkODIwODM0YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CtPs8TXBnACQvQ8OQZ82PihgXJx4yIduqkoPA_hnSL0)

Fix in last commit, please check it again @agustingroh

2024-07-08 10:44 UTC, agustingroh approved these changes

2024-07-08 10:56 UTC, merged